# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-16.04"
 
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.network "private_network", ip: "10.50.1.100"

  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

  config.vm.provision "shell", inline: <<-EOC
    sudo mkdir -p ~/.ssh
    sudo cp /home/vagrant/.ssh/authorized_keys ~/.ssh/authorized_keys

    sudo sed -i -e "\\#PasswordAuthentication yes# s#PasswordAuthentication yes#PasswordAuthentication no#g" /etc/ssh/sshd_config
    sudo systemctl restart sshd.service
    echo "finished"
  EOC

  ansible_vars = { deploy_host: "viafront3.com", admin_email: "test@viafront3.com", local: true }
  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = "postfix.yml"
    ansible.extra_vars = ansible_vars
  end

end
